# workflow for communication with eps1lon/mui-scripts-incubator
# These scripts are experimental. We have a very "dumb" workflow here that is only responsible for triggering
# actions in eps1lon/mui-scripts-incubator. Since those actions are experimental they'll likely break
# and we don't want to disrupt the normal repo workflow.
name: experimental
on: status
jobs:
  if: github.event.state == "success" && github.event.sender.login == "netlify[bot]" && github.event.description == "Deploy preview ready!"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo ${{ github.event.state }}
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.sender.id }}
          echo ${{ github.event.sender.type }}
          echo ${{ github.event.name }}
          echo ${{ github.event.description }}
      - name: Find PR associated with this push
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run mui-scripts a11y-snapshot
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MUI_SCRIPTS_INCUBATOR }}
          repository: eps1lon/mui-scripts-incubator
          event-type: a11y-snapshot
          client-payload: '{ "pr_number": "${{ steps.findPr.outputs.pr }}"}'
